### PR TITLE
build: Use npm ci

### PR DESCRIPTION
**Pull request by alpha14**

### CODE REVIEW

**Review by Docteur-RS — COMMENTED** [review]
I don't know anything about npm ci....But seems legit lol.

**Comment by alpha14** [comment]
It is useful for deployments and more predictable than npm install
https://docs.npmjs.com/cli/v8/commands/npm-ci

**Comment by Docteur-RS** [comment]
From the doc you quoted : The project **must** have an existing package-lock.json or npm-shrinkwrap.json.

I don't see any at project root.

**Comment by alpha14** [comment]
It's present in the PR:
https://github.com/altertek/whatimupto/blob/fcad279cf78784a570cbf82e04f4cdcde04df9d6/package-lock.json

**Review by Docteur-RS — APPROVED** [review]

**Pull request merged**
